PerlAlien/Alien-Build

lib/Alien/Build/Plugin/Fetch/NetFTP.pm

Hello.
Support downloading files from FTP on machines behind NAT or firewall.

try to use passive ftp mode when active fails

---

lib/Alien/Build/MM.pm

Not much more to say than is already in the commit message. 
Related to #12

fix typo: preifx

---

lib/Alien/Build.pm

It makes things easier when developing plugins and the like.

Sort the keys of the state hash

---

lib/Alien/Build/Manual/FAQ.pod
lib/Alien/Build/Plugin/PkgConfig/CommandLine.pm
lib/Alien/Build/Plugin/PkgConfig/LibPkgConf.pm
lib/Alien/Build/Plugin/PkgConfig/Negotiate.pm
lib/Alien/Build/Plugin/PkgConfig/PP.pm
t/alien_build_plugin_pkgconfig_commandline.t
t/alien_build_plugin_pkgconfig_libpkgconf.t
t/alien_build_plugin_pkgconfig_negotiate.t
t/alien_build_plugin_pkgconfig_pp.t

add atleast_version, exact_version and max_version to pkg-config plugins.

---

Changes
dist.ini
lib/Alien/Build/Plugin/PkgConfig/Negotiate.pm
t/00_diag.t
t/alien_build_plugin_pkgconfig_commandline.t
t/alien_build_plugin_pkgconfig_negotiate__pick.t

prefer PkgConfig::PP on MSWin32 where it is more reliable

---

lib/Alien/Build/Plugin/Extract/ArchiveZip.pm
lib/Alien/Build/Plugin/Extract/CommandLine.pm
lib/Alien/Build/Plugin/Extract/Negotiate.pm
t/alien_build_plugin_extract_negotiate.t

prefer commandline over archivezip for .zip files

---

.travis.yml
dist.ini
lib/Alien/Build/Plugin/Download/Negotiate.pm
lib/Alien/Build/Plugin/Extract/CommandLine.pm
lib/Alien/Build/Plugin/Fetch/CurlCommand.pm
lib/Alien/Build/Plugin/Fetch/HTTPTiny.pm
lib/Alien/Build/Plugin/Fetch/Wget.pm
lib/Alien/Build/Util.pm
t/alien_build_plugin_download_negotiate.t
t/alien_build_plugin_fetch_httptiny.t
t/alien_build_util.t

prefer Fetch::CurlCommand in some sensible situations

---

.cirrus.yml
README.md
t/cip/needs-alien-unzip/Dockerfile
t/cip/needs-alien-unzip/t/needs_alien_unzip.t

add cirrus ci

---

.appveyor.yml
README.md
lib/Alien/Build.pm
lib/Alien/Build/Plugin/PkgConfig/CommandLine.pm
lib/Alien/Build/Plugin/PkgConfig/LibPkgConf.pm
lib/Alien/Build/Plugin/PkgConfig/PP.pm
lib/Alien/Build/Plugin/Probe/CBuilder.pm
lib/Alien/Build/Plugin/Probe/CommandLine.pm
t/alien_build.t
t/alien_build_plugin_pkgconfig_commandline.t
t/alien_build_plugin_probe_cbuilder.t

Add version probe hook property

---

README.md
lib/Alien/Build.pm
lib/Alien/Build/Manual/Alien.pod
lib/Alien/Build/Manual/AlienUser.pod
lib/Alien/Build/Manual/Contributing.pod
lib/Alien/Build/Plugin/Prefer/BadVersion.pm
lib/Alien/Build/Plugin/Prefer/GoodVersion.pm

including details about using ALIEN_INSTALL_TYPE as an opt-in (#104)

documentation updates

---

lib/Alien/Base.pm

put everything in INC

---

Changes
lib/Alien/Build/Plugin/Download/Negotiate.pm
t/alien_build_plugin_download_negotiate.t

Interface to override the default decoder to help test #115

override decoder

---

lib/Alien/Build/MM.pm

Fix for https://github.com/Perl5-Alien/Alien-Libxml2/issues/7 #118

add make alien_clean target

---

Changes
README.md
lib/Alien/Build.pm
lib/Alien/Build/MM.pm
lib/Alien/Build/Manual/PluginAuthor.pod
lib/Alien/Build/Plugin/Core/CleanInstall.pm
lib/Test/Alien/Build.pm
t/01_use.t
t/alien_build_plugin_core_cleaninstall.t

add clean_install hook

---

Changes.Alien-Build-Decode-Mojo
dist.ini
lib/Alien/Build/Plugin/Decode/Mojo.pm
maint/cip-before-install
t/00_diag.t
t/alien_build_plugin_decode_mojo.t

This PR will merge the `Decode::Mojo` plugin into `Alien-Build` core, as per #115

Merge Alien-Build-Plugin-Decode-Mojo

---

Changes
lib/Alien/Build/Plugin/Probe/CBuilder.pm
lib/Test/Alien/Build.pm
t/alien_build_plugin_probe_cbuilder__live.t

manage noexec on /tmp for cbuilder plugin

---

Changes
lib/Test/Alien.pm
t/test_alien.t

See 
https://github.com/Perl5-Alien/Test-Alien-CPP/issues/3
https://github.com/Perl5-Alien/Test-Alien-CPP/pull/4

Add cbuilder_config option to xs_ok

---

lib/Alien/Build/Manual/AlienAuthor.pod

After briefly reviewing this manual I found a couple of nits that annoyed me.

updates to author doco

---

Changes
author.yml
lib/Alien/Base/Wrapper.pm
lib/Alien/Build/Manual/AlienUser.pod
t/alien_base_wrapper.t

ABW improvements

---

Changes

Fix was accidentally pushed directly to `master`.  Creating this PR to run it through CI.
0b75aff5e2bf0b7c95499a25cc4cb06ca87b4a9b

use current directoy configure only on windows

---

Changes
lib/Alien/Build/Interpolate.pm
lib/Alien/Build/Interpolate/Default.pm
t/alien_build_interpolate.t
t/alien_build_interpolate_default.t

This also refactors the innerds of how helpers work.

try to use the already installed version of some of these tools

---

Changes
example/bzip2.alienfile
example/curl.alienfile
example/dontpanic.alienfile
example/gmake.alienfile
example/openssl.alienfile
example/xz-manual.alienfile
example/xz.alienfile
lib/Alien/Build/Manual/AlienAuthor.pod
lib/Alien/Build/Manual/FAQ.pod
lib/alienfile.pm

This is intended to address #110 
For the FAQ I'd like to see if I can find some representative diagnostics.

a note about dynamci vs. static

---

Changes
lib/Alien/Build/Interpolate/Default.pm
lib/alienfile.pm

Prefer gmake or nmake over dmake on windows

---

lib/Alien/Build/Plugin/Build/Autoconf.pm

We should copy the .dll files from bin to dynamic on windows, because autohell can't be easily coerced into doing this for us.  Who knows why.

copy .dll from bin to dynamic

---

Changes
lib/Test/Alien.pm

workaround for cygwin's buggy faux fork

---

t/alien_build_util.t

Remove call to ls in test

---

.travis.yml
Changes
lib/Alien/Build/Plugin/PkgConfig/LibPkgConf.pm

```
t/alien_build_plugin_pkgconfig_commandline.t ......... ok   
t/alien_build_plugin_pkgconfig_libpkgconf.t .......... 1/?             # Failed test at t/alien_build_plugin_pkgconfig_libpkgconf.t line 74.
t/alien_build_plugin_pkgconfig_libpkgconf.t .......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests 
t/alien_build_plugin_pkgconfig_makestatic.t .......... ok   
```

Test fail on arm64 with pkgconf plugin

---

Changes
t/alien_build_plugin_build_copy.t

adjust copy plugin test to work on msys Perl

---

lib/Test/Alien.pm

Fixes issue #214 on my machine.

Fixes issue #214

---

Changes
lib/Alien/Build/Util.pm

_mirror: check symlink before directory

---

Changes
lib/Test/Alien.pm
t/test_alien.t
t/test_alien_run.t

diagnostic when using Test::Alien tools sans alien_ok

---

Changes
lib/Alien/Base.pm
lib/Alien/Build/Manual/AlienAuthor.pod
lib/Alien/Build/Manual/AlienUser.pod
lib/Alien/Build/Manual/FAQ.pod
lib/Alien/Build/Manual/PluginAuthor.pod
lib/Alien/Build/Plugin/Extract.pod
lib/Alien/Build/Plugin/PkgConfig/CommandLine.pm
lib/Alien/Build/Plugin/PkgConfig/LibPkgConf.pm
lib/Alien/Build/Plugin/PkgConfig/Negotiate.pm
lib/Alien/Build/Plugin/PkgConfig/PP.pm
lib/Alien/Build/Plugin/Prefer.pod
lib/Alien/Build/Plugin/Probe.pod
lib/Alien/Role.pm

improve alt config documentation

---

Changes
lib/Test/Alien.pm

This should hopefully fix #217

Remove duplicate use of lddlfalgs in Test::Alien

---

Changes
lib/Alien/Base.pm
lib/Alien/Build.pm

add .runtime.inline_auto_include property

---

Changes
lib/Alien/Build.pm
lib/Alien/Build/Interpolate.pm
t/alien_build.t
t/alien_build_interpolate.t

interpolation enhancements

---

t/alien_build_plugin_fetch_localdir.t

refactored this test while working on something else I thought was a bug but turned out to be just fine.  May as well keep the refactor though, since it is a minor improvement.

refactor test

---

Changes
lib/Alien/Build/Plugin.pm
lib/Alien/Build/Plugin/Build.pod
lib/Alien/Build/Plugin/Core.pod
lib/Alien/Build/Plugin/Decode.pod
lib/Alien/Build/Plugin/Digest.pod
lib/Alien/Build/Plugin/Extract.pod
lib/Alien/Build/Plugin/Fetch.pod
lib/Alien/Build/Plugin/Gather.pod
lib/Alien/Build/Plugin/PkgConfig.pod
lib/Alien/Build/Plugin/Prefer.pod
lib/Alien/Build/Plugin/Probe.pod
lib/Alien/Build/Plugin/Test.pod

improve POD indexes

---

Changes
lib/Alien/Build.pm
t/alien_build_plugin_fetch_wget.t

This is part of the work for #190

compute download_rule as soon as possible

---

Changes
lib/Alien/Base.pm
lib/Test/Alien/Diag.pm

handle undef in Test::Alien::Diag better

---

maint/ci-test-plugins.pl

until this is resolved:
https://github.com/jjatria/Alien-premake5/issues/1

disable testing with Alien::premake5

---

Changes
example/README

fix readme

---

Changes
example/user/tool/lib/LZMA/Example.pm

push onto the correct list

---

Changes
lib/Alien/Build/Plugin/Extract/ArchiveTar.pm
lib/Alien/Build/Plugin/Extract/Negotiate.pm
t/alien_build_plugin_extract_archivetar.t

Add support for tar.xz files for the pure perl extractor plugin

---

lib/Alien/Build.pm
t/alien_build_plugin_core_cleaninstall.t

support clean_install for system installs
