lib/Alien/Build/Plugin/Extract/CommandLine.pm
t/alien_build_plugin_extract_commandline_tar_can.t

This bug was uncovered by this `map { }` over a constant list in `Dist::Zilla::Plugin::AlienBuild`: <https://github.com/plicease/Dist-Zilla-Plugin-AlienBuild/blob/v0.23/lib/Dist/Zilla/Plugin/AlienBuild.pm#L253>.

Fix bug with read-only dynamically scoped $_

---

lib/alienfile.pm

This patch fixes some minor typos ("verson" instead of "version") in the `alienfile.pm` POD.

Fix typos: s/verson/version/

---

lib/Alien/Build/Plugin/Extract/ArchiveZip.pm
lib/Alien/Build/Plugin/Fetch/CurlCommand.pm
lib/Alien/Build/Plugin/Fetch/HTTPTiny.pm
lib/Alien/Build/Plugin/Fetch/LWP.pm
lib/Alien/Build/Plugin/Fetch/Local.pm
lib/Alien/Build/Plugin/Fetch/LocalDir.pm
lib/Alien/Build/Plugin/Fetch/NetFTP.pm
lib/Alien/Build/Plugin/Gather/IsolateDynamic.pm
lib/Alien/Build/Plugin/Prefer/BadVersion.pm

I noticed some of the included plugins had abstracts that were repeated from other modules (eg. Gather::IsolateDynamic and Fetch::HTTPTiny had the abstract for Fetch::LWP).
This cosmetic patch fixes that, and also makes some small changes to the abstract of some other plugins, to make them a bit more predictable. But of course, you can feel free to cherry pick that commit out if you prefer.

Abstract fix

---

corpus/cmake-libpalindrome/CMakeLists.txt

CMake defaults to C++ language. If C++ compiler is not installed, cmake dies
when performing t/alien_build_plugin_build_cmake.t test:
$ perl -Ilib t/alien_build_plugin_build_cmake.t
not ok 1 - basic {
ok 1 - alienfile compiles
not ok 2 - alien builds okay
This patch fixes the corpus/cmake-libpalindrome's CMakeLists.txt to specify
libpalindrome is written in C. This frees Alien-Build tests from dependncy on
C++ compiler.

corpus/cmake-libpalindrome is in C

---

lib/Alien/Build/Manual/FAQ.pod
lib/alienfile.pm
t/alienfile.t

The idea has always been for authors of Alien distributions to use the simplified but powerful-enough `alienfile` syntax and for the `$build->meta` interface to be for plugin authors.  It is sometimes necessary for Alien authors to get under the hood with `meta->{after,around,before}_hook` to customize things, so we do provide that as an interface in a pinch, but anytime you need to do that for more than one or two Aliens we should reconsider the `alienfile` interface to make it more powerful.
One thing that you really need to be able to do is have a callback called after the gather stage for alienized packages that have borken `.pc` files (other issues can also make this a helpful technique as well).  This patch provides an interface to the `after_hook` and `before_hook` API to make this …

Add before and after directives to alienfile

---

.travis.yml
Changes
lib/Alien/Build.pm
lib/Alien/Build/MM.pm
lib/Alien/Build/Plugin/Test/Mock.pm
lib/Test/Alien/Build.pm
t/01_use.t
t/alien_build_plugin_test_mock.t
t/test_alien_build.t
t/test_alien_canplatypus.t

This PR will address #64 and #65.  The idea is to improve the testing of `Alien::Build` plugins.  Progress:

Improve Alien::Build plugin testing

---

t/test_alien_run.t

This is the only fail from a cpantest report on haiku:
```
t/test_alien_canplatypus.t ........................... ok
t/test_alien_run.t ................................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests 
```
http://www.cpantesters.org/cpan/report/79b969fc-2ef2-11e9-b46c-d3780df0180e
The diagnostic might be wrong, but it doesn't seem that important, so relax the test a little on haiku.

more relaxed diagnostic testing for haiku

---

lib/Alien/Base.pm
t/alien_base.t

Currently slightly in process. One thing still TODO:
* Does ->version_cmp need documenting, so subclass authors know how they can override it?

Add some version comparison methods to Alien::Base (fixes #75)

---

Changes
README.md
lib/Alien/Base.pm
lib/Alien/Build.pm
lib/Alien/Build/MM.pm

I think it might make sense from a documentation perspective to group class methods load and resume with constructors.

reclassify some class methods as constructors

---

inc/probebad.pl

These reports from ct are annoying:
```
t/01_use.t ........................................... ok
t/alien_base.t ....................................... ok
t/alien_base__system_installed.t ..................... skipped: test requires Alien::Base::ModuleBuild
t/alien_base_pkgconfig.t ............................. ok
t/alien_base_wrapper.t ............................... ok
t/alien_build.t ...................................... 
Dubious, test returned 2 (wstat 512, 0x200)
```
check for this bad configuration and fail with exit 0 at configure time.

check tmpdir

---

lib/Alien/Base.pm

This will help with #107, although I think there may need to be some updates to EU::D as well.

For Inline::C / ExtUtils::Depends: split INC flags off the rest of cflags

---

lib/Test/Alien.pm

This patch changes the ordering that `-l` extra linker flags are added in `xs_ok`.
* kiwiroy/Test-Alien-CPP#1
* [successful alien::edlib](https://travis-ci.com/kiwiroy/p5-alien-edlib/builds/111138264)
* [successful alien::build](https://travis-ci.com/kiwiroy/Alien-Build/builds/111135436)

Alien -l (el) flags first

---

Changes
lib/Alien/Build/Plugin/Decode/Mojo.pm
lib/Alien/Build/Plugin/Download/Negotiate.pm
t/alien_build_plugin_download_negotiate.t
t/alien_build_plugin_fetch_curlcommand.t

This makes the `Decode::Mojo` plugin the default for the download negotiator. #115

Switch to using Decode::Mojo instead of Decode::HTML

---

Changes
lib/Alien/Build.pm
lib/Alien/Build/Plugin/Core/Gather.pm
t/alien_build_plugin_core_gather.t

->canonical(1) gives us a reproducible build.
->ascii will encode in an ascii format which may save us some trouble

use ->canonical and ->ascii to make json dumps more reliable

---

Changes
lib/Test/Alien.pm
t/test_alien.t

WIP implementation that requires testing for #138

try to catch SEGV inside with_subtest to provide a better diagnostic.

---

Changes
lib/Alien/Build/Plugin/Extract/CommandLine.pm

I learned recently that Windows 10 now comes with `bsdtar`!  Only it calls it `tar`.  We should prefer it over `ptar`.

use the system / bsdtar on windows if avail

---

Changes
lib/Alien/Build/Plugin/Decode/Mojo.pm

This adds a little state to the `Decode::Mojo` plugin, and will hopefully help out with schizophrenic weridisms like this maybe:
```
Output from './Build':
Can't locate Mojo/DOM58.pm in @INC (you may need to install the Mojo::DOM58 module) (@INC contains: inc inc /opt/perl-5.31.8/lib/site_perl/5.31.8/x86_64-linux /opt/perl-5.31.8/lib/site_perl/5.31.8 /opt/perl-5.31.8/lib/5.31.8/x86_64-linux /opt/perl-5.31.8/lib/5.31.8 .) at /opt/perl-5.31.8/lib/site_perl/5.31.8/Alien/Build.pm line 306.
Building Acme-Alien-DontPanic2
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
```

remember which Mojo::DOM we are using

---

Changes
lib/Alien/Build/Plugin/Decode/Mojo.pm
lib/Alien/Build/Plugin/Download/Negotiate.pm
t/alien_build_plugin_download_negotiate.t

We switched to using `Mojo::DOM` or `Mojo::DOM58` for decode since those are pure perl, and the older `Decode::HTML` had a dependency on `HTML::Parser` which is XS.  Unfortunately if AB gets upgraded between the config and build steps that can confuse the download and decode negotiation and it can require `HTML::Parser` in the config step and `Mojo::DOM*` in the build step when it is too late to change the prereqs and you will get an error trying to load `Mojo::DOM*`.  Ideally you don't change the AB between config and build, but it can happen sometimes.
To solve this we will use the older `HTML::Parser` plugin if `HTML::Parser` is already installed.  This is a good thing to do anyway, because it saves the prereq for `Mojo::DOM*` since AB has the capability to use `HTML::Parser` if …

Sometimes prefer Decode::HTML plugin if HTML::Parser is already installed.

---

Changes
lib/Alien/Build/Plugin/Probe/Vcpkg.pm

The version probe hook property was missing from the original implementation of the `Probe::Vcpkg` plugin.

set version property on probe hook

---

lib/Alien/Build/Plugin/Prefer/SortVersions.pm

This PR protects against `version` regular expressions that have multiple capture groups - as is done on line 73.
https://github.com/Perl5-Alien/Alien-Build/blob/3771402e802fdb866909e38ebc6e69a9297b6264/lib/Alien/Build/Plugin/Prefer/SortVersions.pm#L73

Minor fix to Prefer::SortVersions plugin

---

lib/Alien/Base.pm
t/alien_base.t

[WIP]
As discussed in https://github.com/Perl5-Alien/Alien-curl/issues/10#issuecomment-596263491 
Still to do:

Add dynamic_bin_dir method

---

lib/Alien/Build/MM.pm

I'm still not 100% confident about makefile syntax, but this at least runs without complaint on my own machine and on CI.  I don't think any of the tests check installation, though, and clean_install is certainly not tested.
The postamble sections look to be unaffected by parallelisation, as each of those targets has only singular dependencies.
The big block of concatenated strings might also be better as a heredoc.  
updates #197

Makefile: add targets to disable parallel installs

---

lib/Alien/Build/Plugin/Download/Negotiate.pm
lib/Alien/Build/Plugin/Prefer/BadVersion.pm
lib/Alien/Build/Plugin/Prefer/GoodVersion.pm

Plugin::Prefer::BadVersion is useful to know about when there are versions that should be skipped in an alienfile download phase.  
Plugin::Prefer::GoodVersion is listed for symmetry.
The first commit is not really related, but fixes some minor typos.

Add Plugin::Prefer::BadVersion and Plugin::Prefer::GoodVersion to the See Also section

---

lib/Alien/Base.pm

Should be the last one - I found no others.

Second single-colon typo in package name

---

Changes
lib/Alien/Build/Plugin/Build/Copy.pm
lib/Alien/Build/Plugin/PkgConfig/CommandLine.pm
lib/Alien/Build/Plugin/PkgConfig/LibPkgConf.pm
lib/Alien/Build/Plugin/PkgConfig/PP.pm
lib/Alien/Build/Plugin/Probe/CBuilder.pm
lib/Alien/Build/Plugin/Probe/Vcpkg.pm
t/alien_build_plugin_build_copy.t
t/alien_build_plugin_pkgconfig_commandline.t
t/alien_build_plugin_pkgconfig_libpkgconf.t
t/alien_build_plugin_pkgconfig_pp.t
t/alien_build_plugin_probe_cbuilder.t
t/alien_build_plugin_probe_cbuilder__live.t
t/alien_build_plugin_probe_vcpkg.t

This is mainly for `Alien::Libxml2`, which uses multiple probe methods.  In this configuration if one probe or pkg-config plugin fails in the probe step, its gather step may still execute and populate libs cflags, etc.  This patch fixes that oversight.  This should finally put https://github.com/PerlAlien/Alien-Libxml2/issues/23 and similar to bed.

safer pure-perl pkgconfig with multiple probes

---

.github/workflows/macos.yml
.github/workflows/windows.yml

Replaced by appending to `$GITHUB_PATH` environment file.
See <https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/>.

GitHub Actions: Use of `add-path` command has been deprecated

---

.github/workflows/msys2-mingw.yml
lib/Alien/Build/Plugin/PkgConfig/CommandLine.pm
lib/Test/Alien.pm

- Add GitHub Actions Workflow for MSYS2/MINGW.
- Only dereference arrayref if arrayref. Otherwise this fails when `@gather` contains a coderef.
- Fix `Test::Alien` module name generation so that `ExtUtils::CBuilder` creates a unique `image-base` address from the DLL name.

MSYS2-MINGW CI workflow and fixes

---

.github/workflows/linux.yml

These got disabled at some point, but maybe we want to keep them.

re-enable the plugins test

---

lib/Alien/Build/Plugin/Build/Copy.pm

Quote target to accomodate spaces in Build::Copy

---

lib/Alien/Build/Plugin/Build/Autoconf.pm

The existing documentation isn't quite correct, and I think discussing CONFIG_SITE first is helpful here, since we both use the existing value and override it.

update doco on environment variables for Build::Autoconf plugin

---

lib/Alien/Build/Plugin/Probe/CBuilder.pm

Probe::CBuilder: die with $error instead of $@

---

lib/Alien/Build/Plugin/Probe/CBuilder.pm
lib/Alien/Build/Plugin/Probe/CommandLine.pm
t/alien_build_plugin_probe_cbuilder.t
t/alien_build_plugin_probe_commandline.t

Updates #299
Let me know if you want me to rework the commits.  Currently they include some false starts using Sort::Versions which maybe you don't want in the commit history.

add atleast_version arg support to Probe::CommandLine and Probe::CBuilder plugins

---

Changes
lib/Alien/Base.pm
lib/Alien/Build/Plugin.pm
lib/Alien/Build/Plugin/Probe/CBuilder.pm
lib/Alien/Build/Plugin/Probe/CommandLine.pm
lib/Alien/Util.pm
t/alien_util.t

This PR adds an `Alien::Util` module for things that are needed by both the `Alien::Base` runtime and `Alien::Build` build-time without either having to depend on the other.  So far the only function is `version_cmp`, which used to live in `Alien::Base` as a class method, but was used in some of the probe plugins with #300

Add Alien::Util, and move version_cmp there

---

.cirrus.yml
Changes
lib/Alien/Base/Wrapper.pm
t/lib/MyTest/HaveCompiler.pm
t/test_alien.t
t/test_alien_cancompile.t

A test that really does require a compiler slipped through the screen.  I've also silenced a few warnings, though others still remain.

Fix support for systems without a compiler

---

Changes
author.yml
lib/Alien/Build/Plugin.pm
t/alien_build_plugin.t

This was deprecated fairly early on, and was never used widely.

remove subplugin method

---

.github/workflows/linux.yml
maint/ci-test-plugins.pl
maint/cip-before-install
t/alien_build_plugin_fetch_curlcommand.t

test more plugins in CI

---

author.yml
lib/Alien/Build.pm
lib/Alien/Build/Plugin/Core/Setup.pm
t/alien_build_plugin_core_setup.t

Adds a pure Perl implementation for checking the number of available CPUs.
I have not yet added support for this to `::Build::Make`, but I can see adding
the appropriate flag (e.g., `-j`) being enabled automatically (which will
sometimes show upstream bugs if the upstream that is being built does not
specify dependencies properly)
Detects the most common architectures and maps them to common names (roughly
the names of Debian ports).  I'm leaving room for possible future extensions
such as adding ARM versions as another property if needed.
Leaving out `mips`, `mipsel`, `mips64el`, `ppc64el`, `s390x` for now as I
rarely see pre-compiled binaries for those distributed now.
I decided against adding GPU/integrated graphics hardware vendor/capabilities
detection (e.g., Nvidia CUDA) as that is …

Add CPU properties for count and architecture name

---

maint/ci-test-plugins.pl

#354 got most of the CPAN Plugins in CI, but `Alien::Build::Download::GitHub` isn't digest safe yet.

test ABP::Download::GitHub in CI

---

Changes
lib/Alien/Build/Plugin/Core/Download.pm

Caveat: the filter stage should not modify the `$res` passed in, but that doesn't actually stop it from doing that :/
before:
```
Alien::Build::Plugin::Core::Download> decoding html
no matching files in listing at /home/ollisg/opt/perl/5.37.5/lib/site_perl/5.37.5/Alien/Build/Plugin/Core/Download.pm line 61.
Recipe did not seem to download a file or directory
```
after:
```
Alien::Build::Plugin::Core::Download> decoding html
Alien::Build::Plugin::Core::Download> These files were excluded by the filter stage:
Alien::Build::Plugin::Core::Download> excluded https://ftp.gnu.org/gnu/make/?C=N;O=D
Alien::Build::Plugin::Core::Download> excluded https://ftp.gnu.org/gnu/make/?C=M;O=A
Alien::Build::Plugin::Core::Download> excluded https://ftp.gnu.org/gnu/make/?C=S;O=A …
```

better diagnostic when filter excludes all

---

Changes
lib/Alien/Base.pm

Previous PR at <https://github.com/PerlAlien/Alien-Build/pull/328>.

Fix to give .runtime.inline_auto_include priority

---

t/test_alien.t

When Perl is installed in a directory with a space, one test fails. This change makes it work.

quote-protect against "Perl in space"

---

.github/workflows/linux.yml
Changes
lib/Alien/Build/Plugin/Core/Setup.pm

for #411 
apparently archname could use arm64- as a prefix in addition to aarch64- (on FreeBSD anyway)

add arm64- prefix detection

---

README.md
lib/Alien/Base.pm
lib/Alien/Build.pm
t/alien_base.t

This avoids potential typos in code returning false negatives.
I looked for places to add tests for the Alien::Build variants but it was unclear where they should be added.  Potentially `alien_install_type_is` could be adapted to use these methods but it is perhaps best left alone. 
Updates #418

Add is_{system|share}_install methods

---

lib/Alien/Build/Plugin/Build/Autoconf.pm
t/alien_build_plugin_build_autoconf.t

While looking at https://github.com/PDLPorters/pdl/issues/498 I wanted to update Alien::proj on my Windows "in space" setup to try to reproduce the problem. The `autoconf` stuff in Alien::sqlite failed. This is a partial fix for that.
This quote-protects the prefix path (where Perl is installed) so `configure` doesn't get the wrong args. It also adds `--disable-dependency-tracking` which seems like it will always be fine, and prevented the next failure, which was in makefile fragments inclusion. The failure after that seems to be because the `autoconf` stuff is getting various compiler components that have spaces in their paths, and putting newlines instead of the spaces. I couldn't find where `configure` was doing that, and have figured out a more idiomatic way to test Proj in any case, …

Fix some perl-in-space problems

---

lib/Alien/Build/Plugin/Core/Setup.pm

This is to avoid following warning on OpenIndiana:
```
Architecture detection: Unknown archname 'i86pc-solaris-thread-multi-64'. at /usr/perl5/vendor_perl/5.40/Alien/Build/Plugin/Core/Setup.pm line 248.
```

CPU arch support for illumos
